Repository vektor-inc/vk-all-in-one-expansion-unit, pull requests merged in 2023-10, with the labels that each got.

#1023 【確認待ち】SNS のシェアボタンの表示ロジックを修正
  inc/sns/function-sns-btns.php
  readme.txt
  tests/test-sns-btns.php
Labels: 優先度：中

#1022 【確認待ち】[ 広告アラート ] チェックボックスの表記をスラッグじゃなくてラベル名に
  inc/promotion-alert.php
  readme.txt
Labels: 優先度：中

#1021 【確認待ち】[ 投稿タイプマネージャー ] 投稿タイプの設定を保存した時に自動的にパーマリンク保存
  inc/post-type-manager/package/class.post-type-manager.php
  readme.txt
Labels: 優先度：中

#1031 CF7のreCAPCHAがフォーム以外のページで表示されないようにする処理を追加
  inc/contactform7-asset-optimize.php
  readme.txt
  vkExUnit.php
Labels: 優先度：高

#1038 プロフィールウィジェットの Twitter アイコンを X アイコンに変更
  assets/_scss/vkExUnit_style.scss
  assets/css/vkExUnit_style.css
  inc/other-widget/widget-profile.php
  readme.txt
Labels: 優先度：高, 確認待ち

#1042 【確認待ち】SNS ブロックがサイトエディタで表示されるように
  inc/call-to-action/package/block/build/block.asset.php
  inc/call-to-action/package/block/build/block.js
  inc/child-page-index/block/build/block.asset.php
  inc/child-page-index/block/build/block.js
  inc/contact-section/block/build/block.asset.php
  inc/contact-section/block/build/block.js
  inc/page-list-ancestor/block/build/block.asset.php
  inc/page-list-ancestor/block/build/block.js
  inc/sitemap-page/block/build/block.asset.php
  inc/sitemap-page/block/build/block.js
  inc/sns/block/build/block.asset.php
  inc/sns/block/build/block.js
  inc/sns/function-sns-btns.php
  package-lock.json
  readme.txt
Labels: 優先度：高, 確認待ち

#1044 【2人目確認中】広告アラートの投稿タイプのチェックボックスを修正
  inc/promotion-alert.php
  readme.txt
Labels: 優先度：超高, 確認待ち
