Repository vektor-inc/vk-all-in-one-expansion-unit, pull requests merged in 2025-04, with the labels that each got.

#1191 [ Bug fix ][ SNS ] ExUnit Main Setting の Warning に対処
  inc/sns/sns.php
  readme.txt
Labels: 優先度：中, 確認待ち

#1189 [ 機能追加 ][ カスタム投稿タイプ設定 ] oEmbed制御用の is_embeddable 対応の設定項目を追加
  inc/post-type-manager/package/class.post-type-manager.php
  readme.txt
Labels: 優先度：超高

#1195 [ 不具合修正 ][ カスタム投稿タイプ設定 ] 埋め込み設定のチェックボックスにチェックを入れても保存されないのを解消
  inc/post-type-manager/package/class.post-type-manager.php
  readme.txt
Labels: bug, 優先度：超高
